### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by s0u5j1i9n** [neurosim/DNN_NeuroSim_V1.3#11]
Hello, 
First of all, I've learned a lot about NeuroSIM.  Really thank you. 
I've tried NeuroSIM benchmark with inference.py, but I often have difficulties. 

Can you help me for the below problem? 
 
I had gotten the below message.
===============================================
/bin/bash: ./layer_record_VGG8/trace_command.sh: No such file or directory
===============================================

So I changed last line of inference.py as below. 
===============================================
call(["/bin/bash", './layer_record_'+str(args.model)+'/trace_command.sh']) →     call(["/bin/bash"], './layer_record_'+str(args.model)+'/trace_command.sh',shell=True)
===============================================

And I got the below error. 
Do you have any idea on "TypeError: bufsize must be an integer" ?
===============================================
  File "DNS/DNN_NeuroSim_V1.3-master/DNN_NeuroSim_V1.3-master/Inference_pytorch/inference.py", line 152, in <module>
    call(["/bin/bash"], './layer_record_'+str(args.model)+'/trace_command.sh',shell=True)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/subprocess.py", line 287, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/subprocess.py", line 629, in __init__
    raise TypeError("bufsize must be an integer")
TypeError: bufsize must be an integer
===============================================

**Comment by neurosim** [comment]
Sorry I never face this problem before. Are you sure the files in "layer_record_VGG8" folder are successfully generated? There should be some excel files containing the real trace of input and weight data, and a trace_command shell file generated during the running of inferenc.py.
