### ISSUE TITLE
signed computation

### ISSUE THREAD

**Issue by SaBaKa2020** [neurosim/DNN_NeuroSim_V1.3#14]
For the purpose of signed computation, is negative weights are supported by the simulator? If so, could you please explain how it should be implemented in a simulation?
Just for the context: it is very common to perform signed computation using differential conductance of a pair of memristors.

**Comment by neurosim** [comment]
Hi! In this simulator, we map the signed weights to the positive memory values, and assume a reference array to offset the bias. This version doesn't support the way of using differential pairs to represent signed weights. But it should not be very difficult to support that kind of mapping. Please contact us with more details if you need help with the code modification.

**Comment by SaBaKa2020** [comment]
Thanks for the answer.
If I understand correctly, in this current version you can only have positive weights unless the weights are binary. Is that correct?

**Comment by neurosim** [comment]
Yes, correct.
