### ISSUE TITLE
Usage of `adderTreeNM` is used in `bufferOutputCM`

### ISSUE THREAD

**Issue by sepehrMSP** [neurosim/DNN_NeuroSim_V1.3#15]
Hi,
In the `ProcessingUnit.cpp`, in `ProcessingUnitCalculatePerformance` function, in the following else clause:
https://github.com/neurosim/DNN_NeuroSim_V1.3/blob/930c75772d43c733eb3090a5636761e058a16520/Inference_pytorch/NeuroSIM/ProcessingUnit.cpp#L542
 which is used for `conventional` method, in the `CalculatePower` and `CalculateLatency` functions, `adderTreeNM` is used. However, I think it should be `adderTreeCM`.
@neurosim @alu75

**Comment by neurosim** [comment]
Thanks for pointing it out! The typo has been corrected.
