### ISSUE TITLE
`slSwitchMatrix.CalculatePower` in `SubArray.cpp`

### ISSUE THREAD

**Issue by sepehrMSP** [neurosim/DNN_NeuroSim_V1.3#16]
Why in `SubArray.cpp`, in the calculation of power, the first parameter of the following function, which is `numRead`, is set to zero?
`slSwitchMatrix.CalculatePower(0, 2*numWriteOperationPerRow*numRow*activityRowWrite, activityRowRead, activityColWrite);`
On the other hand since `activityRowWrite` is never set, the second argument , which is `numWrite`, is also zero. So we have neither reads nor writes for `slSwitchMatrix`.
@neurosim

**Comment by neurosim** [comment]
Hi! The `slSwitchMatrix` is only used when writing the memory array. The SLs are float when reading. And in this inference version, we only consider the reading operation. Thus only the area of `slSwitchMatrix` is truly in use.
