### ISSUE TITLE
`SubArray::CalculatePower` is just used when `CalculateclkFreq` is false

### ISSUE THREAD

**Issue by sepehrMSP** [neurosim/DNN_NeuroSim_V1.3#18]
Hi, Why `SubArray::CalculatePower` function is just used when the `CalculateclkFreq` is set to `false`. Based the previous issues, if I want to use the synchronous mode, this parameter should be `true`.
@neurosim

**Comment by neurosim** [comment]
Hi! When using the synchronous mode, the `CalculateclkFreq` is set to `true` first to compute the clock frequency. After that, it will be set to `false` to compute the latency and energy. The framework will go through the `CalculatePerformance` functions twice in total.
