### ISSUE TITLE
error when running inference script

### ISSUE THREAD

**Issue by SaBaKa2020** [neurosim/DNN_NeuroSim_V1.3#2]
Hi,
When I run inference.py, an error is raised after trace_command.sh is called. The error is "free(): double free detected in tcache 2".
My configs are ubuntu 20.04 focal, gcc 9.3, cuda 10.1, cuDNN 7.5.0, python 3.6, pytorch 1.1.0 (according to the suggestions in the user manual).
I appreciate it if you could help me resolving the issue.

**Comment by msabri1372** [comment]
Hi 
I have a same error and I have spent a lot of time to solve it.Please help us.

**Comment by parthoBhoumk** [comment]
Hello, 
I also ran into the same error. If anyone has resolved the issue please let me know?

**Comment by msabri1372** [comment]
I tested in the diffrent server and my problem have been solved! Try another GPU!

**Comment by parthoBhoumk** [comment]
I dont have another laptop  / GPU :( 

Can i run it on google colab?? any idea?

**Comment by msabri1372** [comment]
I have tested it on university server. I am unfamiliar with Google Colab,you should try it.

**Comment by parthoBhoumk** [comment]
another question...i have installed exactly the versions mentioned above...did you try the same? if not then please can you tell me about all the versions that you have tried with??

**Comment by msabri1372** [comment]
yes.I have instslled the same version that mentioned in the DNN NeuroSim V1.3 Manual . I have used conda to install them. firstly I have face the same problems and spent lots of time to address them but I couldn't solve them. By changing the GPU, it was solved. I recommend you to update your GPU driver and try it agin.

**Comment by parthoBhoumk** [comment]
Hey can you tell me which GPU you have used in your university server?

**Comment by ZimingYuan** [comment]
I also met the same error and solved it by modifying the makefile of NeuroSim: remove the "-O3" compile flag. It seems the compiler's optimization caused the error but I don't know why.

**Comment by datMaffin** [comment]
I was able to fix the crashing by adding missing return statements. (Got the idea because of https://github.com/neurosim/MLP_NeuroSim_V3.0/pull/4 )

*  `Inference_pytorch/NeuroSIM/Chip.cpp` at the end of `double ChipCalculatePerformance(...)`
  (I added a `return 0;`)
* `Inference_pytorch/NeuroSIM/ProcessingUnit.cpp` at the end of `double ProcessingUnitCalculatePerformance(...)`
  (I, again, added a `return 0;`)
