### ISSUE TITLE
`TileSize > 4*param->numRowSubArray`

### ISSUE THREAD

**Issue by sepehrMSP** [neurosim/DNN_NeuroSim_V1.3#20]
Hi, can you explain the reason of this condition (used in `chipFloorPlan`)? 
`XTileSize > 4 * param->numRowSubArray`
It is logical that `TileSize` be greater than `numRowSubArray`, however I cannot understand why `4` is used? it could be a meaningful parameter.
@neurosim

**Comment by neurosim** [comment]
This condition is used for conventional mapping. We assume a memory hierarchy from sub-array to processing element and to tile. To keep the hierarchy, there are at least 2 sub-arrays in one PE and at least 2 PEs in one tile, therefore, there are at least 4 sub-arrays in one tile. 
And for novel mapping, the condition is `maxPESizeNM < 2*param->numRowSubArray` to make sure at least 2 subarrays in one PE, and there are normally 3*3 PEs in one tile (corresponding to the kernel size).
