### ISSUE TITLE
Question for conductance variation

### ISSUE THREAD

**Issue by iku11** [neurosim/DNN_NeuroSim_V1.3#26]
Thank you for the great tool!

I'm currently using DNN NeuroSim v1.3 to evaluate the off-chip training performance of my memristor.

Have some questions for the conductance variation in the train.py and inference.py file.

1) Should I use the conductance variation in percentage value in following code? 

parser.add_argument('--vari', default=0, help='conductance variation (e.g. 0.1 standard deviation to generate random variation)')

I'm bit curious whether I should use 0.05 or 5 if i have a memristor with 5% cycle to cycle conductance variation.

2) Is the conductance variation in above argument cycle-to-cycle or device-to-device?

Again, thank you for the great tool.

**Comment by neurosim** [comment]
Hi! Thanks for using NeuroSim. Firstly, I want to declare that this version of NeuroSim only supports on-chip inference. The train.py is only used for quantized training. If you want to evaluate on-chip training performance, we have another version designed for it: https://github.com/neurosim/DNN_NeuroSim_V2.1
And for your questions, the conductance variation is the device-to-device variation in this version. But both of them are considered in the training version (DNN_NeuroSim_V2.1). And you should use 0.05 for 5% variation.
