### ISSUE TITLE
Creating network.csv files 

### ISSUE THREAD

**Issue by harshari** [neurosim/DNN_NeuroSim_V1.3#27]
Hello, thank you for NeuroSim. I want to implement some other Network like ResNet50 on ImageNet dataset or VGG19 on CIFAR100. What is the suggestive way of creating the Network.csv file for any other network and dataset we use? Is it getting generated through the pytorch .pth models as we define or we create it manually? 

Regards

**Comment by neurosim** [comment]
Hi! Thanks for using NeuroSim. I created the Network.csv file manually. But you could try to print the layer information (e.g., in_channels, out_channels, kernel_size, stride) from the pytorch model, which might help you to create it.
