### ISSUE TITLE
the mapping method from FP32 weight to synaptic condutance

### ISSUE THREAD

**Issue by JoyKwan** [neurosim/DNN_NeuroSim_V1.3#29]
Hello, neurosim, I've learned a lot from Neurosim.
But I have some quick questions about the mapping method from FP32 weight to synaptic condutance,
Firstly, 
why don't you use the more common differential method(A signed kernel weight is mapped to the differential conductance of a pair of memristors used in the paper _Fully hardware-implemented memristor convolutional neural network_(https://www.nature.com/articles/s41586-020-1942-4)?
Secondly,
The fig.18 in DNN_Neurosim_v1.3_manual.pdf is a little bit strange, why 0.8906 mapped to 15 while 0.9187(>0.8906) mapped to 14(<15)? Is there a formula for this mapping method?

Kind Regards,

Joy Kwan

**Comment by neurosim** [comment]
Hi Joy, thanks for your interest in NeuroSim. 
Yes, the differential mapping is common, but it requires twice devices.
The problem about fig.18 is a typo I think. There is no reason to map 0.8906 to 15 while 0.9187 to 14. It's just a schematic and sorry that we didn't check very carefully.
