### ISSUE TITLE
argument --wl_weight handled as "str" type

### ISSUE THREAD

**Issue by DavidSe7enLynch** [neurosim/DNN_NeuroSim_V1.3#30]
These arguments were treated as "str" type (the default value is "int" type, so no problem if not manually set their values like "--wl_weight 4").
By adding a type conversion in quantization_cpu_np_infer.py like this, the bug could be fixed.

self.wl_weight = int(wl_weight)
self.wl_activate = int(wl_activate)
self.wl_error = int(wl_error)
self.wl_input = int(wl_input)

**Comment by neurosim** [comment]
Thanks for your suggestion. We specify the type in the argparse to avoid this bug now.
