### ISSUE TITLE
question about network.csv

### ISSUE THREAD

**Issue by Zhaoshixin-sky** [neurosim/DNN_NeuroSim_V1.3#33]
![image](https://user-images.githubusercontent.com/61320867/162213885-9bebdbda-52f7-4e4b-97f7-3a41016417d8.png)
The manual does not mention the last column. It indicates stride?
![image](https://user-images.githubusercontent.com/61320867/162214111-e74066d3-da78-44f5-a2a3-7ddf4189d136.png)

**Comment by neurosim** [comment]
Correct!
