### ISSUE TITLE
can not find initialization of activityColWrite etc.

### ISSUE THREAD

**Issue by fishfishfishfishfish** [neurosim/DNN_NeuroSim_V1.3#40]
Hello! It seems that the `activityColWrite`, `activityRowWrite` of `SubArray` class are not initialized or assigned a value anywhere. Could you please tell me the meaning of these variables? Thank you! @alu75

**Comment by neurosim** [comment]
Hi! These two variables can be ignored because they are prepared for the training version. For this inference version, we assume all the parameters have been pre-programmed/written into the memory array, and only reading is needed to do the computation for inference.
