### ISSUE TITLE
System requirements (Linux) 

### ISSUE THREAD

**Issue by radhe-2022** [neurosim/DNN_NeuroSim_V1.3#41]
Does it support on latest versions of ubuntu or redhat????

The recommended one in manual are (1) Red Hat 7.8 (Maipo), gcc v4.8.5, glibc v2.17, 
(2) Ubuntu 16.04, gcc v5.5.0, glibc v2.23.

But It seems this OS are little older.. so is neuroSIM compatible with latest updates in OS

@neurosim @alu75

**Comment by neurosim** [comment]
Yes, it's compatible with latest versions. We are using (1) Ubuntu 18.04, gcc v7.5.0, glibc v2.27 and (2) Red Hat 8.7 (Ootpa), gcc v8.5.0,  glibc v2.28, and everything work well. We will update the manual for next release and thanks for the reminder.

**Comment by radhe-2022** [comment]
Any tentative date for the next release??
