### ISSUE TITLE
net=VGG8，inference=1，训练速度很慢

### ISSUE THREAD

**Issue by zhangfeixiang222** [neurosim/DNN_NeuroSim_V1.3#5]
请问有什么方法可以加快训练速度吗

**Comment by neurosim** [comment]
Please set inference as 0 during training. The label "inference" means considering hardware effects in feed-forward in the code, while training is assumed run by software in this NeuroSim version. If you want to consider the hardware effects during training (on-chip training), please using the training version of NeuroSim.
